#!/usr/bin/env python3
"""
screen_ph4.py — Screen ligands against an Apo2ph4 pharmacophore model using CDPKit.

Reads a pharmacophore model (.pml) generated by Apo2ph4's apo2ph4_generate_ph4.py,
then scores actives and decoys SDF files against it. Outputs a CSV suitable for
ROC-AUC / enrichment factor computation.

Usage:
    python screen_ph4.py \
        --pharmacophore cluster_0_ph4.pml \
        --actives actives_final.sdf \
        --decoys decoys_final.sdf \
        --out screening_results.csv

Dependencies: CDPKit (pip install cdpkit)
"""

import argparse
import math
import sys
import os

import CDPL.Pharm as Pharm
import CDPL.Chem as Chem
import CDPL.Base as Base
import CDPL.MolProp as MolProp


def load_query_pharmacophore(pml_path: str) -> list:
    """
    Load a pharmacophore model from a PML file and return it as a list of
    feature dicts with keys: type, pos(xyz), tolerance, geometry, orientation, length.
    """
    ifs = Base.FileIOStream(pml_path, 'r')
    reader = Pharm.PMLPharmacophoreReader(ifs)
    pharm = Pharm.BasicPharmacophore()
    features = []

    while reader.read(pharm):
        for ftr in pharm:
            ftr_type = Pharm.getType(ftr)
            pos_str = str(Chem.get3DCoordinates(ftr))[4:-1].split(',')
            pos = (float(pos_str[0]), float(pos_str[1]), float(pos_str[2]))
            tolerance = Pharm.getTolerance(ftr)
            geometry = Pharm.getGeometry(ftr)

            orientation = None
            length = None
            if geometry in (Pharm.FeatureGeometry.VECTOR, Pharm.FeatureGeometry.PLANE):
                orient_str = str(Pharm.getOrientation(ftr))[4:-1].split(',')
                orientation = (float(orient_str[0]), float(orient_str[1]), float(orient_str[2]))
                length = Pharm.getLength(ftr)

            features.append({
                'type': ftr_type,
                'pos': pos,
                'tolerance': tolerance,
                'geometry': geometry,
                'orientation': orientation,
                'length': length,
            })

    ifs.close()
    return features


def generate_ligand_features(mol) -> list:
    """
    Generate pharmacophore features for a single ligand molecule using CDPKit.
    Returns list of feature dicts in the same format as load_query_pharmacophore.
    """
    try:
        Chem.perceiveSSSR(mol, False)
        Chem.setRingFlags(mol, False)
        Chem.calcImplicitHydrogenCounts(mol, False)
        Chem.perceiveHybridizationStates(mol, False)
        Chem.setAromaticityFlags(mol, False)
        MolProp.calcAtomHydrophobicities(mol, False)

        lig_pharm = Pharm.BasicPharmacophore()
        pharm_gen = Pharm.DefaultPharmacophoreGenerator()
        pharm_gen.generate(mol, lig_pharm)

        features = []
        for ftr in lig_pharm:
            ftr_type = Pharm.getType(ftr)
            pos_str = str(Chem.get3DCoordinates(ftr))[4:-1].split(',')
            pos = (float(pos_str[0]), float(pos_str[1]), float(pos_str[2]))
            tolerance = Pharm.getTolerance(ftr)
            geometry = Pharm.getGeometry(ftr)

            orientation = None
            length = None
            if geometry in (Pharm.FeatureGeometry.VECTOR, Pharm.FeatureGeometry.PLANE):
                orient_str = str(Pharm.getOrientation(ftr))[4:-1].split(',')
                orientation = (float(orient_str[0]), float(orient_str[1]), float(orient_str[2]))
                length = Pharm.getLength(ftr)

            features.append({
                'type': ftr_type,
                'pos': pos,
                'tolerance': tolerance,
                'geometry': geometry,
                'orientation': orientation,
                'length': length,
            })

        return features
    except Exception as e:
        print(f"  Warning: feature generation failed: {e}", file=sys.stderr)
        return []


def euclidean(p1, p2):
    return math.sqrt(sum((a - b) ** 2 for a, b in zip(p1, p2)))


def cosine_similarity(v1, v2):
    """Cosine between two vectors. Returns 0 if either is zero-length."""
    mag1 = math.sqrt(sum(x * x for x in v1))
    mag2 = math.sqrt(sum(x * x for x in v2))
    if mag1 < 1e-10 or mag2 < 1e-10:
        return 0.0
    return sum(a * b for a, b in zip(v1, v2)) / (mag1 * mag2)


def feature_matches(query_feat, lig_feat, max_dist=2.0):
    """
    Check whether a ligand feature matches a query pharmacophore feature.

    For sphere features: check distance ≤ tolerance
    For vector features (HBD/HBA): check distance ≤ tolerance AND compatible direction
    For plane features (aromatic): check distance ≤ tolerance AND compatible normal

    Returns float match score [0, 1].
    1 = perfect match, 0 = no match.
    """
    if query_feat['type'] != lig_feat['type']:
        return 0.0

    dist = euclidean(query_feat['pos'], lig_feat['pos'])
    tolerance = query_feat['tolerance']
    if tolerance <= 0:
        tolerance = 1.5  # default

    if dist > tolerance + 1.0:  # generous margin
        return 0.0

    # Distance score: Gaussian falloff within tolerance
    dist_score = math.exp(-(dist ** 2) / (2.0 * (tolerance / 2.0) ** 2))

    # For vector features, check direction compatibility
    if query_feat['geometry'] == Pharm.FeatureGeometry.VECTOR:
        if query_feat['orientation'] and lig_feat['orientation']:
            # For HBD: query orientation points FROM feature center TOWARD donor
            # For HBA: query orientation points FROM feature center TOWARD acceptor
            # Ligand feature orientation depends on the generator
            cos = cosine_similarity(query_feat['orientation'], lig_feat['orientation'])
            # Require roughly same direction (cos > 0) but don't be too strict
            if cos < -0.3:
                return 0.0
            dir_score = max(0.0, cos)
            return dist_score * 0.7 + dir_score * 0.3

    # For plane features (aromatic)
    if query_feat['geometry'] == Pharm.FeatureGeometry.PLANE:
        if query_feat['orientation'] and lig_feat['orientation']:
            cos = abs(cosine_similarity(query_feat['orientation'], lig_feat['orientation']))
            if cos < 0.5:  # planes should be roughly parallel
                return 0.0
            return dist_score * 0.7 + cos * 0.3

    # Sphere features (hydrophobic, ionizable, exclusion)
    return dist_score


def score_ligand(query_features, lig_features):
    """
    Compute a pharmacophore match score for a ligand.

    For each query feature, finds the best-matching ligand feature (greedy).
    Final score = mean of per-query-feature best-match scores.
    Returns float in [0, 1].
    """
    if not query_features:
        return 0.0
    if not lig_features:
        return 0.0

    used = [False] * len(lig_features)
    total_score = 0.0

    for qf in query_features:
        best_score = 0.0
        best_idx = -1
        for j, lf in enumerate(lig_features):
            if used[j]:
                continue
            score = feature_matches(qf, lf)
            if score > best_score:
                best_score = score
                best_idx = j
        total_score += best_score
        if best_idx >= 0 and best_score > 0.1:
            used[best_idx] = True

    return total_score / len(query_features)


def read_sdf_mols(sdf_path: str):
    """Read all molecules from an SDF file. Returns list of Chem.Molecule."""
    reader = Chem.MoleculeReader(sdf_path)
    mols = []
    mol = Chem.BasicMolecule()
    while reader.read(mol):
        mols.append(mol)
        mol = Chem.BasicMolecule()
    reader.close()
    return mols


def main():
    parser = argparse.ArgumentParser(description="Screen ligands against an Apo2ph4 pharmacophore model")
    parser.add_argument('--pharmacophore', required=True, help='Path to .pml pharmacophore model')
    parser.add_argument('--actives', required=True, help='Path to actives SDF file')
    parser.add_argument('--decoys', required=True, help='Path to decoys SDF file')
    parser.add_argument('--out', required=True, help='Output CSV path')
    args = parser.parse_args()

    # Load query pharmacophore
    print(f"Loading pharmacophore: {args.pharmacophore}")
    query_features = load_query_pharmacophore(args.pharmacophore)
    non_excl = [f for f in query_features if f['type'] != Pharm.FeatureType.EXCLUSION_VOLUME]
    excl = [f for f in query_features if f['type'] == Pharm.FeatureType.EXCLUSION_VOLUME]
    print(f"  {len(non_excl)} pharmacophore features, {len(excl)} exclusion volumes")

    # Load molecules
    print(f"Loading actives: {args.actives}")
    actives = read_sdf_mols(args.actives)
    print(f"  {len(actives)} actives loaded")

    print(f"Loading decoys: {args.decoys}")
    decoys = read_sdf_mols(args.decoys)
    print(f"  {len(decoys)} decoys loaded")

    # Score all molecules
    results = []

    for label, mols in [('active', actives), ('decoy', decoys)]:
        for i, mol in enumerate(mols):
            if mol.getNumAtoms() == 0:
                continue

            lig_feats = generate_ligand_features(mol)
            if not lig_feats:
                results.append({'molecule_id': f"{label}_{i}", 'score': 0.0, 'label': 1 if label == 'active' else 0})
                continue

            score = score_ligand(query_features, lig_feats)

            # Exclusion volume penalty: if ligand features fall inside exclusion spheres
            excl_penalty = 0.0
            if excl:
                for ef in excl:
                    for lf in lig_feats:
                        d = euclidean(ef['pos'], lf['pos'])
                        if d < ef['tolerance']:
                            excl_penalty += 1.0
                            break
                excl_penalty = min(excl_penalty / max(len(excl), 1), 1.0)

            final_score = score * (1.0 - 0.5 * excl_penalty)

            results.append({
                'molecule_id': f"{label}_{i}",
                'score': round(final_score, 4),
                'label': 1 if label == 'active' else 0,
            })

            if (i + 1) % 100 == 0:
                print(f"  {label}: {i + 1}/{len(mols)} scored...")

    # Write results
    import pandas as pd
    df = pd.DataFrame(results)
    df.to_csv(args.out, index=False)
    print(f"\nResults written to {args.out}")
    print(f"  {len(df)} molecules scored")
    print(f"  Score range: [{df['score'].min():.4f}, {df['score'].max():.4f}]")

    # Quick ROC-AUC
    try:
        from sklearn.metrics import roc_auc_score
        auc = roc_auc_score(df['label'], df['score'])
        print(f"  ROC-AUC: {auc:.4f}")
    except ImportError:
        print("  (install scikit-learn for ROC-AUC)")


if __name__ == '__main__':
    main()
